import React from 'react';
import { FlatList, ScrollView, TextInput, View } from 'react-native';
import { COLORS } from '../constants';
import { categoryLabel, t } from '../i18n';
import s from '../appStyles';
import { Chip, Empty, Section, TransactionRow } from '../components/AppPrimitives';

export default function ActivityScreen({ lang, query, setQuery, filterType, setFilterType, filterWallet, setFilterWallet, filterCategory, setFilterCategory, filterPeriod, setFilterPeriod, clearFilters, settings, activityCategories, filteredTransactions, transactions, remove, openEdit, openAdd, m }) {
  return <View style={s.screen}><Section title={t(lang,'allActivity','All activity')} action={(query||filterType!=='all'||filterWallet!=='all'||filterCategory!=='all'||filterPeriod!=='all')?t(lang,'clear','Clear'):null} onPress={clearFilters}/><TextInput value={query} onChangeText={setQuery} placeholder={t(lang,'searchPlaceholder','Search note, category, amount…')} placeholderTextColor={COLORS.muted} style={s.search}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Chip label={t(lang,'all','All')} active={filterType==='all'} onPress={()=>{setFilterType('all');setFilterCategory('all');}}/><Chip label={t(lang,'expense','Expense')} active={filterType==='expense'} onPress={()=>{setFilterType('expense');setFilterCategory('all');}}/><Chip label={t(lang,'income','Income')} active={filterType==='income'} onPress={()=>{setFilterType('income');setFilterCategory('all');}}/><Chip label={t(lang,'thisMonth','This month')} active={filterPeriod==='month'} onPress={()=>setFilterPeriod(filterPeriod==='month'?'all':'month')}/></ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Chip label={t(lang,'allWallets','All wallets')} active={filterWallet==='all'} onPress={()=>setFilterWallet('all')}/>{settings.wallets.map(wallet=><Chip key={wallet.id} label={wallet.name} active={filterWallet===wallet.id} onPress={()=>setFilterWallet(wallet.id)}/>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Chip label={t(lang,'allCategories','All categories')} active={filterCategory==='all'} onPress={()=>setFilterCategory('all')}/>{activityCategories.map(name=><Chip key={name} label={categoryLabel(name,lang)} active={filterCategory===name} onPress={()=>setFilterCategory(name)}/>)}</ScrollView>{filteredTransactions.length?<FlatList data={filteredTransactions} keyExtractor={x=>x.id} showsVerticalScrollIndicator={false} contentContainerStyle={s.listPad} renderItem={({item})=><View style={s.listSingle}><TransactionRow item={item} settings={settings} money={m} onDelete={remove} onEdit={openEdit} wallets={settings.wallets} customCategories={settings.customCategories}/></View>}/>:<Empty onAdd={()=>openAdd()} filtered={transactions.length>0} language={lang}/>}</View>;
}
