import React from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import NepalTools from '../components/NepalTools';
import PlanningTools from '../components/PlanningTools';
import SavingsGoals from '../components/SavingsGoals';
import HouseholdBudgets from '../components/HouseholdBudgets';
import PlanningSnapshot from '../components/PlanningSnapshot';
import SmartInsights from '../components/SmartInsights';
import { categoryLabel, t } from '../i18n';
import s from '../appStyles';
import { Section } from '../components/AppPrimitives';
const { dailyAverage } = require('../domain/finance');

export default function InsightsScreen({ lang, breakdown, m, transactions, currentMonth, today, summary, settings, remittance, udharo, nepalData, eventStatuses, obligationStatuses, savingsStatuses, householdStatuses, planningSummary, smartInsights, onAddRecurringSuggestion, remindersEnabled, reminderPermission, onOpenReminders, setSettingsOpen, setRemittanceOpen, setPaymentRecord, setUdhaaroOpen, setEventOpen, setObligationOpen, setPaymentObligation, setSavingsOpen, setSavingsMovement, setHouseholdOpen, setTab, openAdd }) {
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}><Section title={t(lang,'insights','Spending insights')}/><View style={s.insightRow}><View style={s.insight}><Text style={s.kicker}>{t(lang,'topCategory','TOP CATEGORY').toUpperCase()}</Text><Text style={s.insightBig}>{breakdown[0]?categoryLabel(breakdown[0].category,lang):'—'}</Text><Text style={s.meta}>{breakdown[0]?m(breakdown[0].amount):(lang==='ne'?'अहिलेसम्म खर्च छैन':'No spending yet')}</Text></View><View style={s.insight}><Text style={s.kicker}>{t(lang,'dailyAverage','DAILY AVERAGE').toUpperCase()}</Text><Text style={s.insightBig}>{m(dailyAverage(transactions,currentMonth,today))}</Text><Text style={s.meta}>{t(lang,'basedThisMonth','Based on this month')}</Text></View></View><View style={s.form}><Text style={s.kicker}>{t(lang,'monthSnapshot','MONTH SNAPSHOT').toUpperCase()}</Text><Text style={s.cardTitle}>{lang==='ne'?`यो महिना ${m(summary.monthExpense)} खर्च भएको छ।`:`You have spent ${m(summary.monthExpense)} this month.`}</Text><Text style={[s.meta,{marginTop:8}]}>{t(lang,'addExpensesHint','Add expenses consistently for a clearer pattern over time.')}</Text></View><SmartInsights settings={settings} money={m} comparison={smartInsights?.comparison} savings={smartInsights?.savings} forecast={smartInsights?.forecast} unusual={smartInsights?.unusual} suggestions={smartInsights?.recurringSuggestions} onAddSuggestion={onAddRecurringSuggestion}/><Pressable style={s.secondary} onPress={onOpenReminders} accessibilityRole="button"><Text style={s.secondaryText}>🔔 {t(lang,'reminders','Reminders')} · {remindersEnabled&&reminderPermission?t(lang,'on','On'):t(lang,'off','Off')}</Text></Pressable><PlanningSnapshot settings={settings} money={m} analytics={planningSummary}/><PlanningTools settings={settings} money={m} statuses={obligationStatuses} onAdd={()=>{setPaymentObligation(null);setObligationOpen(true);}} onPay={(item)=>{setPaymentObligation({obligation:item,status:item});setObligationOpen(true);}}/><SavingsGoals settings={settings} money={m} statuses={savingsStatuses} onAdd={()=>{setSavingsMovement(null);setSavingsOpen(true);}} onDeposit={(goal)=>{setSavingsMovement({goal,status:goal,direction:'deposit'});setSavingsOpen(true);}} onWithdraw={(goal)=>{setSavingsMovement({goal,status:goal,direction:'withdrawal'});setSavingsOpen(true);}}/><HouseholdBudgets settings={settings} money={m} statuses={householdStatuses} onAdd={()=>setHouseholdOpen(true)}/><NepalTools settings={settings} money={m} remittance={remittance} udharo={udharo} udharoRecords={nepalData.udharo} eventStatuses={eventStatuses} onSettings={()=>setSettingsOpen(true)} onAddRemittance={()=>setRemittanceOpen(true)} onAddUdhaaro={()=>{setPaymentRecord(null);setUdhaaroOpen(true);}} onPayUdhaaro={(record)=>{setPaymentRecord(record);setUdhaaroOpen(true);}} onAddEvent={()=>setEventOpen(true)} onAddEventExpense={(eventId)=>{setTab('overview');openAdd(eventId);}}/></ScrollView>;
}
