import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS } from '../constants';
import { t } from '../i18n';

export default function CategoryModal({ visible, onClose, onSave, language = 'en' }) {
  const [type,setType]=useState('expense'),[name,setName]=useState(''),[emoji,setEmoji]=useState('✨');
  useEffect(()=>{if(visible){setType('expense');setName('');setEmoji('✨');}},[visible]);
  function submit(){const trimmed=name.trim();if(!trimmed)return Alert.alert('Name the category','Enter a category name.');onSave({type,item:{id:`category-${Date.now()}`,name:trimmed,emoji:emoji.trim()||'✨'}});}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><Text style={s.title}>{language==='ne'?'आफ्नै श्रेणी':'Custom category'}</Text><Text style={s.muted}>{language==='ne'?'खर्चालाई तपाईंको वास्तविक खर्चअनुसार बनाउनुहोस्।':'Make Kharcha match how you actually spend.'}</Text><View style={s.segmented}>{['expense','income'].map(key=><Pressable key={key} onPress={()=>setType(key)} style={[s.segment,type===key&&s.segmentActive]}><Text style={[s.segmentText,type===key&&s.segmentTextActive]}>{key==='expense'?t(language,'expense','Expense'):t(language,'income','Income')}</Text></Pressable>)}</View><Text style={s.label}>{language==='ne'?'नाम':'Name'}</Text><TextInput value={name} onChangeText={setName} placeholder="Khaja, Tuition…" placeholderTextColor={COLORS.muted} style={s.input}/><Text style={s.label}>Emoji</Text><TextInput value={emoji} onChangeText={setEmoji} placeholder="✨" placeholderTextColor={COLORS.muted} style={s.input}/><Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>{t(language,'addCategory','Add category')}</Text></Pressable></View></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(38,39,48,.42)'},sheet:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:COLORS.surface,borderTopLeftRadius:20,borderTopRightRadius:20,borderWidth:1,borderColor:COLORS.border,padding:20,paddingBottom:28},title:{color:COLORS.text,fontSize:22,fontWeight:'600'},muted:{color:COLORS.muted,fontSize:13,marginTop:4},segmented:{flexDirection:'row',backgroundColor:COLORS.surface,padding:4,borderRadius:10,marginTop:18},segment:{flex:1,height:44,alignItems:'center',justifyContent:'center',borderRadius:10},segmentActive:{backgroundColor:COLORS.surface2},segmentText:{color:COLORS.muted,fontWeight:'600'},segmentTextActive:{color:COLORS.text},label:{color:COLORS.text,fontSize:12,fontWeight:'600',marginTop:16,marginBottom:7},input:{height:48,borderRadius:10,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface2,color:COLORS.text,paddingHorizontal:12},primary:{height:48,borderRadius:10,marginTop:20,backgroundColor:COLORS.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:COLORS.onAccent,fontSize:15,fontWeight:'600'}});
