import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS } from '../constants';
import { EVENT_PRESETS, eventPresetLabel, t } from '../i18n';
const { normalizeAmount } = require('../domain/finance');
export default function EventBudgetModal({visible,onClose,onSave,settings={}}){
  const lang=settings.language||'en';const [preset,setPreset]=useState('Dashain'),[name,setName]=useState('Dashain'),[budget,setBudget]=useState('');
  useEffect(()=>{if(visible){setPreset('Dashain');setName(eventPresetLabel('Dashain',lang));setBudget('');}},[visible,lang]);
  function choose(next){setPreset(next);setName(eventPresetLabel(next,lang));}
  function submit(){const amount=normalizeAmount(budget);if(!amount)return Alert.alert('Check budget','Enter an amount greater than zero.');if(!name.trim())return Alert.alert('Event name','Enter a name.');onSave({id:`event-${Date.now()}`,preset,name:name.trim(),budget:amount,createdAt:new Date().toISOString()});}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><Text style={s.title}>{t(lang,'festivalEvent','Festival / event')}</Text><Text style={s.muted}>{lang==='ne'?'दशैं, तिहार, विवाह वा यात्राका लागि छुट्टै बजेट राख्नुहोस्।':'Keep a separate budget for Dashain, Tihar, weddings, travel and other events.'}</Text><Text style={s.label}>{t(lang,'festivalEvent','Festival / event')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{EVENT_PRESETS.map(([en,,icon])=><Pressable key={en} onPress={()=>choose(en)} style={[s.chip,preset===en&&s.selected]}><Text>{icon}</Text><Text style={s.chipText}>{eventPresetLabel(en,lang)}</Text></Pressable>)}</ScrollView><Text style={s.label}>{t(lang,'eventName','Event name')}</Text><TextInput value={name} onChangeText={setName} placeholder="Dashain 2083" placeholderTextColor={COLORS.muted} style={s.input}/><Text style={s.label}>{t(lang,'eventBudget','Event budget')}</Text><TextInput value={budget} onChangeText={setBudget} keyboardType="decimal-pad" placeholder="30000" placeholderTextColor={COLORS.muted} style={s.input}/><Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>{t(lang,'save','Save')}</Text></Pressable></View></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.58)'},sheet:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'#10161E',borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:COLORS.border,padding:20,paddingBottom:28},title:{color:COLORS.text,fontSize:22,fontWeight:'900'},muted:{color:COLORS.muted,fontSize:13,lineHeight:19,marginTop:4},label:{color:COLORS.text,fontSize:12,fontWeight:'700',marginTop:16,marginBottom:7},chip:{height:42,paddingHorizontal:12,borderRadius:13,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,flexDirection:'row',gap:6,alignItems:'center',marginRight:8},selected:{borderColor:COLORS.accent,backgroundColor:COLORS.accentSoft},chipText:{color:COLORS.text,fontSize:12,fontWeight:'700'},input:{height:48,borderRadius:14,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface2,color:COLORS.text,paddingHorizontal:12},primary:{height:52,borderRadius:15,marginTop:20,backgroundColor:COLORS.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:'#07130F',fontSize:15,fontWeight:'900'}});
