import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { COLORS } from '../constants';
import { t } from '../i18n';
const { udharoOutstanding } = require('../domain/phaseTwo');
const { transactionDateLabel } = require('../domain/nepal');
function Progress({value}){return <View style={s.track}><View style={[s.fill,{width:`${Math.max(0,Math.min(value,1))*100}%`}]} /></View>;}
function ActionCard({icon,title,copy,onPress}){return <Pressable style={s.actionCard} onPress={onPress}><Text style={s.icon}>{icon}</Text><Text style={s.actionTitle}>{title}</Text><Text style={s.meta}>{copy}</Text></Pressable>;}
export default function NepalTools({settings,money,remittance,udharo,udharoRecords,eventStatuses,onSettings,onAddRemittance,onAddUdharo,onPayUdharo,onAddEvent,onAddEventExpense}){
  const lang=settings.language||'en';
  function displayDate(value){if(!value)return '';try{const result=transactionDateLabel(value,settings);return result.secondary?`${result.primary} · ${result.secondary}`:result.primary;}catch{return value;}}
  return <View><View style={s.sectionHead}><Text style={s.sectionTitle}>{t(lang,'nepalTools','Nepal money tools')}</Text></View><View style={s.grid}><ActionCard icon="🇳🇵" title={t(lang,'settings','Language & calendar')} copy={settings.dateSystem==='both'?'AD + BS':settings.dateSystem} onPress={onSettings}/><ActionCard icon="🌏" title={t(lang,'remittance','Remittance')} copy={`${remittance.count} ${t(lang,'transactions','transactions')}`} onPress={onAddRemittance}/><ActionCard icon="🤝" title={t(lang,'udharo','Udhaaro')} copy={`${money(udharo.lent)} ${t(lang,'lent','lent')}`} onPress={onAddUdharo}/><ActionCard icon="🪔" title={t(lang,'eventBudgets','Festival / event budgets')} copy={`${eventStatuses.length}`} onPress={onAddEvent}/></View>
    <View style={s.summaryRow}><View style={s.summary}><Text style={s.kicker}>{t(lang,'remittanceReceived','Remittance received this month').toUpperCase()}</Text><Text style={s.big}>{money(remittance.nprReceived)}</Text><Text style={s.meta}>{money(remittance.fees)} {t(lang,'fees','fees')}</Text></View><View style={s.summary}><Text style={s.kicker}>{t(lang,'udharo','UDHAARO').toUpperCase()}</Text><Text style={s.big}>{money(udharo.borrowed)}</Text><Text style={s.meta}>{t(lang,'borrowed','borrowed')} · {money(udharo.lent)} {t(lang,'lent','lent')}</Text></View></View>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>{t(lang,'udharo','Udhaaro')}</Text><Pressable onPress={onAddUdharo}><Text style={s.link}>{t(lang,'add','Add')}</Text></Pressable></View><View style={s.list}>{udharoRecords.length?udharoRecords.map(record=>{const outstanding=udharoOutstanding(record);return <View key={record.id} style={s.item}><View style={s.itemCopy}><Text style={s.itemTitle}>{record.person}</Text><Text style={s.meta}>{record.direction==='lent'?t(lang,'lent','Lent'):t(lang,'borrowed','Borrowed')}{record.dueDate?` · ${displayDate(record.dueDate)}`:''}</Text></View><View style={s.itemRight}><Text style={s.itemTitle}>{money(outstanding)}</Text>{outstanding>0?<Pressable onPress={()=>onPayUdharo(record)}><Text style={s.link}>{t(lang,'recordPayment','Record payment')}</Text></Pressable>:<Text style={s.success}>✓</Text>}</View></View>}):<Text style={s.empty}>{t(lang,'noUdharo','No Udhaaro yet.')}</Text>}</View>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>{t(lang,'eventBudgets','Festival / event budgets')}</Text><Pressable onPress={onAddEvent}><Text style={s.link}>{t(lang,'add','Add')}</Text></Pressable></View><View style={s.list}>{eventStatuses.length?eventStatuses.map(event=><View key={event.id} style={s.event}><View style={s.between}><View><Text style={s.itemTitle}>{event.name}</Text><Text style={s.meta}>{money(event.spent)} / {money(event.budget)}</Text></View><Pressable onPress={()=>onAddEventExpense(event.id)}><Text style={s.link}>{t(lang,'addExpense','Add expense')}</Text></Pressable></View><Progress value={event.progress}/>{event.overBy>0?<Text style={s.danger}>+{money(event.overBy)}</Text>:<Text style={s.meta}>{money(event.remaining)} {t(lang,'left','left')}</Text>}</View>):<Text style={s.empty}>{t(lang,'noEvents','No event budgets yet.')}</Text>}</View>
  </View>;
}
const s=StyleSheet.create({sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:24,marginBottom:10},sectionTitle:{color:COLORS.text,fontSize:18,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},actionCard:{width:'48%',minHeight:128,backgroundColor:COLORS.surface,borderRadius:18,borderWidth:1,borderColor:COLORS.border,padding:15},icon:{fontSize:24,marginBottom:12},actionTitle:{color:COLORS.text,fontSize:14,fontWeight:'800'},meta:{color:COLORS.muted,fontSize:12,lineHeight:17,marginTop:4},summaryRow:{flexDirection:'row',gap:10,marginTop:12},summary:{flex:1,minHeight:126,backgroundColor:COLORS.surface,borderRadius:18,borderWidth:1,borderColor:COLORS.border,padding:15,justifyContent:'space-between'},kicker:{color:COLORS.accent,fontSize:9,fontWeight:'800',letterSpacing:1},big:{color:COLORS.text,fontSize:20,fontWeight:'900'},list:{backgroundColor:COLORS.surface,borderRadius:18,borderWidth:1,borderColor:COLORS.border,overflow:'hidden'},item:{minHeight:70,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:COLORS.border},itemCopy:{flex:1},itemRight:{alignItems:'flex-end',marginLeft:10},itemTitle:{color:COLORS.text,fontSize:14,fontWeight:'800'},link:{color:COLORS.accent,fontSize:12,fontWeight:'800'},success:{color:COLORS.accent,fontSize:16},empty:{color:COLORS.muted,padding:16,fontSize:13},event:{padding:14,borderBottomWidth:1,borderBottomColor:COLORS.border},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},track:{height:6,borderRadius:99,backgroundColor:COLORS.surface2,overflow:'hidden',marginTop:10,marginBottom:6},fill:{height:'100%',backgroundColor:COLORS.accent,borderRadius:99},danger:{color:COLORS.danger,fontSize:12}});
