import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS, categoryPairs } from '../constants';
const { isValidIsoDate, normalizeAmount } = require('../domain/finance');
function pad2(v){return String(v).padStart(2,'0');}
function todayIso(){const d=new Date();return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;}

export default function RecurringModal({visible,onClose,onSave,wallets=[],customCategories}){
  const [type,setType]=useState('expense'),[amount,setAmount]=useState(''),[category,setCategory]=useState('Food'),[walletId,setWalletId]=useState('cash'),[frequency,setFrequency]=useState('monthly'),[startDate,setStartDate]=useState(todayIso()),[note,setNote]=useState('');
  useEffect(()=>{if(visible){setType('expense');setAmount('');setCategory('Food');setWalletId(wallets[0]?.id||'cash');setFrequency('monthly');setStartDate(todayIso());setNote('');}},[visible,wallets]);
  const categories=useMemo(()=>categoryPairs(type,customCategories),[type,customCategories]);
  function switchType(next){setType(next);setCategory(next==='expense'?'Food':'Salary');}
  function submit(){const value=normalizeAmount(amount);if(!value)return Alert.alert('Enter an amount','Use a number greater than zero.');if(!isValidIsoDate(startDate))return Alert.alert('Check the start date','Use YYYY-MM-DD.');onSave({id:`recurring-${Date.now()}`,type,amount:value,category,note:note.trim(),walletId,frequency,startDate,active:true});}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><Text style={s.title}>Recurring transaction</Text><Text style={s.muted}>Kharcha will add due entries automatically when the app opens.</Text><View style={s.segmented}>{['expense','income'].map(key=><Pressable key={key} onPress={()=>switchType(key)} style={[s.segment,type===key&&s.segmentActive]}><Text style={[s.segmentText,type===key&&s.segmentTextActive]}>{key==='expense'?'Expense':'Income'}</Text></Pressable>)}</View><Text style={s.label}>Amount</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={COLORS.muted} style={s.input}/><Text style={s.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{categories.map(([name,emoji])=><Pressable key={name} onPress={()=>setCategory(name)} style={[s.chip,category===name&&s.selected]}><Text>{emoji}</Text><Text style={s.chipText}>{name}</Text></Pressable>)}</ScrollView><Text style={s.label}>Wallet</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{wallets.map(wallet=><Pressable key={wallet.id} onPress={()=>setWalletId(wallet.id)} style={[s.chip,walletId===wallet.id&&s.selected]}><Text>{wallet.icon||'👛'}</Text><Text style={s.chipText}>{wallet.name}</Text></Pressable>)}</ScrollView><Text style={s.label}>Repeat</Text><View style={s.segmentedSmall}>{['weekly','monthly'].map(key=><Pressable key={key} onPress={()=>setFrequency(key)} style={[s.segment,frequency===key&&s.segmentActive]}><Text style={[s.segmentText,frequency===key&&s.segmentTextActive]}>{key==='weekly'?'Weekly':'Monthly'}</Text></Pressable>)}</View><View style={s.two}><View style={s.flex}><Text style={s.label}>Start date</Text><TextInput value={startDate} onChangeText={setStartDate} placeholder="YYYY-MM-DD" placeholderTextColor={COLORS.muted} style={s.input}/></View><View style={s.flex}><Text style={s.label}>Note</Text><TextInput value={note} onChangeText={setNote} placeholder="Rent, salary…" placeholderTextColor={COLORS.muted} style={s.input}/></View></View><Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>Save recurring</Text></Pressable></View></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.58)'},sheet:{position:'absolute',left:0,right:0,bottom:0,maxHeight:'94%',backgroundColor:'#10161E',borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:COLORS.border,padding:20,paddingBottom:28},title:{color:COLORS.text,fontSize:22,fontWeight:'900'},muted:{color:COLORS.muted,fontSize:13,marginTop:4},segmented:{flexDirection:'row',backgroundColor:COLORS.surface,padding:4,borderRadius:14,marginTop:18},segmentedSmall:{flexDirection:'row',backgroundColor:COLORS.surface,padding:4,borderRadius:14},segment:{flex:1,height:42,alignItems:'center',justifyContent:'center',borderRadius:11},segmentActive:{backgroundColor:COLORS.surface2},segmentText:{color:COLORS.muted,fontWeight:'700'},segmentTextActive:{color:COLORS.text},label:{color:COLORS.text,fontSize:12,fontWeight:'700',marginTop:14,marginBottom:7},input:{height:48,borderRadius:14,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface2,color:COLORS.text,paddingHorizontal:12},chip:{height:42,paddingHorizontal:12,borderRadius:13,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,flexDirection:'row',gap:6,alignItems:'center',marginRight:8},selected:{borderColor:COLORS.accent,backgroundColor:COLORS.accentSoft},chipText:{color:COLORS.text,fontSize:12,fontWeight:'700'},two:{flexDirection:'row',gap:10},flex:{flex:1},primary:{height:52,borderRadius:15,marginTop:20,backgroundColor:COLORS.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:'#07130F',fontSize:15,fontWeight:'900'}});
