import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS, REMITTANCE_CURRENCIES } from '../constants';
import { t } from '../i18n';
const { normalizeAmount, isValidIsoDate } = require('../domain/finance');
const { inputDateToAd, transactionDateInput } = require('../domain/nepal');
function pad2(v){return String(v).padStart(2,'0');}
function todayIso(){const d=new Date();return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;}
export default function RemittanceModal({visible,onClose,onSave,wallets=[],settings={}}){
  const lang=settings.language||'en';
  const [amount,setAmount]=useState(''),[foreignAmount,setForeignAmount]=useState(''),[currency,setCurrency]=useState('AED'),[fees,setFees]=useState('0'),[sender,setSender]=useState(''),[country,setCountry]=useState(''),[walletId,setWalletId]=useState('cash'),[date,setDate]=useState(todayIso());
  useEffect(()=>{if(!visible)return;setAmount('');setForeignAmount('');setCurrency('AED');setFees('0');setSender('');setCountry('');setWalletId(wallets[0]?.id||'cash');try{setDate(transactionDateInput(todayIso(),settings));}catch{setDate(todayIso());}},[visible,wallets,settings]);
  function submit(){const npr=normalizeAmount(amount);if(!npr)return Alert.alert('Check amount','Enter NPR received.');let ad;try{ad=inputDateToAd(date,settings);}catch{ad=null;}if(!ad||!isValidIsoDate(ad))return Alert.alert('Check date',settings.dateSystem==='BS'?'Enter a valid BS date.':'Use YYYY-MM-DD.');const foreign=Number(String(foreignAmount).replace(/,/g,''))||0;const fee=Number(String(fees).replace(/,/g,''))||0;onSave({id:`remittance-${Date.now()}`,type:'income',amount:npr,category:'Remittance',note:sender.trim()||country.trim()||'Remittance',date:ad,walletId,paymentMethod:'bank',createdAt:new Date().toISOString(),remittance:{sender:sender.trim(),country:country.trim(),currency,foreignAmount:foreign,fees:fee}});}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><ScrollView style={s.sheet} contentContainerStyle={s.body} keyboardShouldPersistTaps="handled"><Text style={s.title}>{t(lang,'addRemittance','Add remittance')}</Text><Text style={s.muted}>{lang==='ne'?'विदेशबाट आएको पैसा र यसको मूल मुद्रा विवरण राख्नुहोस्।':'Record money received from abroad with its original currency details.'}</Text><Text style={s.label}>{t(lang,'nprReceived','NPR received')}</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="100000" placeholderTextColor={COLORS.muted} style={s.input}/><Text style={s.label}>{t(lang,'foreignCurrency','Foreign currency')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{REMITTANCE_CURRENCIES.map(code=><Pressable key={code} onPress={()=>setCurrency(code)} style={[s.chip,currency===code&&s.selected]}><Text style={s.chipText}>{code}</Text></Pressable>)}</ScrollView><View style={s.two}><View style={s.flex}><Text style={s.label}>{t(lang,'foreignAmount','Foreign amount')}</Text><TextInput value={foreignAmount} onChangeText={setForeignAmount} keyboardType="decimal-pad" placeholder="2700" placeholderTextColor={COLORS.muted} style={s.input}/></View><View style={s.flex}><Text style={s.label}>{t(lang,'fees','Fees')}</Text><TextInput value={fees} onChangeText={setFees} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={COLORS.muted} style={s.input}/></View></View><View style={s.two}><View style={s.flex}><Text style={s.label}>{t(lang,'sender','Sender')}</Text><TextInput value={sender} onChangeText={setSender} placeholder="Name" placeholderTextColor={COLORS.muted} style={s.input}/></View><View style={s.flex}><Text style={s.label}>{t(lang,'originCountry','Country')}</Text><TextInput value={country} onChangeText={setCountry} placeholder="UAE, Qatar…" placeholderTextColor={COLORS.muted} style={s.input}/></View></View><Text style={s.label}>{t(lang,'destinationWallet','Destination wallet')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{wallets.map(w=><Pressable key={w.id} onPress={()=>setWalletId(w.id)} style={[s.chip,walletId===w.id&&s.selected]}><Text>{w.icon||'👛'}</Text><Text style={s.chipText}>{w.name}</Text></Pressable>)}</ScrollView><Text style={s.label}>{t(lang,'date','Date')} {settings.dateSystem==='BS'?'(BS)':'(AD)'}</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={COLORS.muted} style={s.input}/><Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>{t(lang,'save','Save')}</Text></Pressable></ScrollView></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.58)'},sheet:{position:'absolute',left:0,right:0,bottom:0,maxHeight:'94%',backgroundColor:COLORS.surface,borderTopLeftRadius:28,borderTopRightRadius:28,borderWidth:1,borderColor:COLORS.border},body:{padding:20,paddingBottom:30},title:{color:COLORS.text,fontSize:22,fontWeight:'900'},muted:{color:COLORS.muted,fontSize:13,lineHeight:19,marginTop:4},label:{color:COLORS.text,fontSize:12,fontWeight:'700',marginTop:14,marginBottom:7},input:{height:48,borderRadius:14,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface2,color:COLORS.text,paddingHorizontal:12},chip:{height:42,paddingHorizontal:12,borderRadius:13,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center',marginRight:8},selected:{borderColor:COLORS.accent,backgroundColor:COLORS.accentSoft},chipText:{color:COLORS.text,fontSize:12,fontWeight:'700'},two:{flexDirection:'row',gap:10},flex:{flex:1},primary:{height:52,borderRadius:15,marginTop:20,backgroundColor:COLORS.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:COLORS.onAccent,fontSize:15,fontWeight:'900'}});
