import React, { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS } from '../constants';
import { t } from '../i18n';
const { normalizeAmount, isValidIsoDate } = require('../domain/finance');
const { inputDateToAd, transactionDateInput } = require('../domain/nepal');
function pad2(v){return String(v).padStart(2,'0');}
function todayIso(){const d=new Date();return `${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;}
export default function UdhaaroModal({visible,onClose,onSave,onPay,paymentRecord,settings={},wallets=[]}){
  const lang=settings.language||'en';const paying=Boolean(paymentRecord);
  const [direction,setDirection]=useState('lent'),[person,setPerson]=useState(''),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState(''),[note,setNote]=useState(''),[paymentDate,setPaymentDate]=useState(todayIso()),[walletId,setWalletId]=useState('cash');
  useEffect(()=>{if(!visible)return;setDirection('lent');setPerson('');setAmount('');setDueDate('');setNote('');setWalletId(wallets[0]?.id||'cash');try{setPaymentDate(transactionDateInput(todayIso(),settings));}catch{setPaymentDate(todayIso());}},[visible,paymentRecord,settings,wallets]);
  function convertDate(value,optional=false){if(!value&&optional)return '';try{return inputDateToAd(value,settings);}catch{return null;}}
  function submit(){const value=normalizeAmount(amount);if(!value)return Alert.alert('Check amount','Enter an amount greater than zero.');if(paying){const ad=convertDate(paymentDate);if(!ad||!isValidIsoDate(ad))return Alert.alert('Check date','Enter a valid date.');if(!walletId)return Alert.alert('Choose wallet','Select the wallet used for this payment.');return onPay(paymentRecord.id,value,ad,walletId);}const due=convertDate(dueDate,true);if(due===null||due&&!isValidIsoDate(due))return Alert.alert('Check due date','Enter a valid date or leave it blank.');if(!person.trim())return Alert.alert('Person required','Enter a name.');onSave({id:`udharo-${Date.now()}`,direction,person:person.trim(),amount:value,dueDate:due,note:note.trim(),repayments:[],status:'active',createdAt:new Date().toISOString()});}
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><Text style={s.title}>{paying?t(lang,'recordPayment','Record payment'):t(lang,'addUdharo','Add Udhaaro')}</Text><Text style={s.muted}>{paying?(paymentRecord?.person||''):(lang==='ne'?'लिएको वा दिएको पैसा र बाँकी रकम सम्झनुहोस्।':'Track money you borrowed or lent and what is still outstanding.')}</Text>{!paying&&<><View style={s.segmented}><Pressable onPress={()=>setDirection('lent')} style={[s.segment,direction==='lent'&&s.segmentActive]}><Text style={[s.segmentText,direction==='lent'&&s.segmentTextActive]}>{t(lang,'lent','Lent')}</Text></Pressable><Pressable onPress={()=>setDirection('borrowed')} style={[s.segment,direction==='borrowed'&&s.segmentActive]}><Text style={[s.segmentText,direction==='borrowed'&&s.segmentTextActive]}>{t(lang,'borrowed','Borrowed')}</Text></Pressable></View><Text style={s.label}>{t(lang,'person','Person')}</Text><TextInput value={person} onChangeText={setPerson} placeholder="Name" placeholderTextColor={COLORS.muted} style={s.input}/></>}<Text style={s.label}>{paying?t(lang,'paymentAmount','Payment amount'):t(lang,'amount','Amount')}</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={COLORS.muted} style={s.input}/>{paying?<><Text style={s.label}>{t(lang,'chooseWallet','Choose wallet')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{wallets.map(wallet=><Pressable key={wallet.id} onPress={()=>setWalletId(wallet.id)} style={[s.walletChip,walletId===wallet.id&&s.walletChipActive]}><Text style={s.walletChipText}>{wallet.icon||'👛'} {wallet.name}</Text></Pressable>)}</ScrollView><Text style={s.label}>{t(lang,'date','Date')} {settings.dateSystem==='BS'?'(BS)':'(AD)'}</Text><TextInput value={paymentDate} onChangeText={setPaymentDate} placeholder="YYYY-MM-DD" placeholderTextColor={COLORS.muted} style={s.input}/></>:<><Text style={s.label}>{t(lang,'dueDate','Due date')} {settings.dateSystem==='BS'?'(BS)':'(AD)'}</Text><TextInput value={dueDate} onChangeText={setDueDate} placeholder="Optional" placeholderTextColor={COLORS.muted} style={s.input}/><Text style={s.label}>{t(lang,'note','Note')}</Text><TextInput value={note} onChangeText={setNote} placeholder="Optional" placeholderTextColor={COLORS.muted} style={s.input}/></>}<Pressable style={s.primary} onPress={submit}><Text style={s.primaryText}>{t(lang,'save','Save')}</Text></Pressable></View></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(38,39,48,.42)'},sheet:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:COLORS.surface,borderTopLeftRadius:20,borderTopRightRadius:20,borderWidth:1,borderColor:COLORS.border,padding:20,paddingBottom:28},title:{color:COLORS.text,fontSize:22,fontWeight:'600'},muted:{color:COLORS.muted,fontSize:13,lineHeight:19,marginTop:4},segmented:{flexDirection:'row',backgroundColor:COLORS.surface,padding:4,borderRadius:10,marginTop:18},segment:{flex:1,height:44,alignItems:'center',justifyContent:'center',borderRadius:10},segmentActive:{backgroundColor:COLORS.surface2},segmentText:{color:COLORS.muted,fontWeight:'600'},segmentTextActive:{color:COLORS.text},label:{color:COLORS.text,fontSize:12,fontWeight:'600',marginTop:14,marginBottom:7},input:{height:48,borderRadius:10,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface2,color:COLORS.text,paddingHorizontal:12},primary:{height:48,borderRadius:10,marginTop:20,backgroundColor:COLORS.accent,alignItems:'center',justifyContent:'center'},walletChip:{height:44,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,alignItems:'center',justifyContent:'center',marginRight:8},walletChipActive:{borderColor:COLORS.accent,backgroundColor:COLORS.accentSoft},walletChipText:{color:COLORS.text,fontSize:12,fontWeight:'600'},primaryText:{color:COLORS.onAccent,fontSize:15,fontWeight:'600'}});
