import { Platform, StyleSheet } from 'react-native';
import { COLORS } from './constants';

const softShadow = Platform.select({
  ios: {
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.055,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
  },
  android: { elevation: 2 },
  default: {},
});

const navShadow = Platform.select({
  ios: {
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -3 },
  },
  android: { elevation: 10 },
  default: {},
});

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  app: { flex: 1, backgroundColor: COLORS.bg },
  center: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },

  top: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eyebrow: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  brand: {
    color: COLORS.text,
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  badge: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dot: { color: COLORS.accent, fontSize: 8 },
  badgeText: { color: COLORS.text, fontSize: 10, fontWeight: '800' },

  content: { flex: 1 },
  scroll: { paddingHorizontal: 20, paddingBottom: 116 },
  screen: { flex: 1, paddingHorizontal: 20 },

  hero: {
    paddingHorizontal: 2,
    paddingTop: 18,
    paddingBottom: 10,
    marginTop: 2,
  },
  heroValue: {
    color: COLORS.text,
    fontSize: 38,
    lineHeight: 46,
    fontWeight: '900',
    letterSpacing: -1.2,
    marginTop: 4,
    marginBottom: 18,
  },
  metrics: { flexDirection: 'row', alignItems: 'center' },
  metric: { flex: 1 },
  metricValue: { fontSize: 16, fontWeight: '800', marginTop: 4 },
  divider: {
    width: 1,
    height: 30,
    backgroundColor: COLORS.border,
    marginHorizontal: 18,
  },
  income: { color: COLORS.income },
  danger: { color: COLORS.danger },

  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginTop: 12,
    ...softShadow,
  },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  kicker: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.9,
  },
  cardTitle: {
    color: COLORS.text,
    fontSize: 19,
    fontWeight: '900',
    marginTop: 4,
    lineHeight: 25,
    letterSpacing: -0.25,
  },
  percent: { color: COLORS.text, fontSize: 17, fontWeight: '900' },
  track: {
    height: 6,
    borderRadius: 999,
    backgroundColor: COLORS.surface2,
    overflow: 'hidden',
    marginTop: 14,
    marginBottom: 10,
  },
  fill: { height: '100%', backgroundColor: COLORS.accent, borderRadius: 999 },
  meta: { color: COLORS.muted, fontSize: 12, lineHeight: 18 },

  sectionHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 10,
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  action: { color: COLORS.accent, fontSize: 12, fontWeight: '800' },

  list: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
    ...softShadow,
  },
  row: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  icon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  iconText: { fontSize: 18 },
  rowCopy: { flex: 1 },
  rowTitle: { color: COLORS.text, fontSize: 14, lineHeight: 19, fontWeight: '800' },
  rowRight: { alignItems: 'flex-end', marginLeft: 8 },
  amount: { fontSize: 14, fontWeight: '900' },
  rowActions: { flexDirection: 'row', gap: 12, marginTop: 5 },
  edit: { color: COLORS.accent, fontSize: 10, fontWeight: '700' },
  delete: { color: COLORS.danger, fontSize: 10, fontWeight: '700' },
  rowDivider: { height: 1, backgroundColor: COLORS.border, marginLeft: 66 },

  empty: {
    alignItems: 'center',
    padding: 28,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    ...softShadow,
  },
  emptyEmoji: { fontSize: 32 },
  emptyTitle: { color: COLORS.text, fontSize: 17, fontWeight: '900', marginTop: 10 },
  emptyCopy: {
    color: COLORS.muted,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
    maxWidth: 280,
  },

  secondary: {
    marginTop: 16,
    paddingHorizontal: 16,
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: COLORS.text, fontSize: 13, fontWeight: '800' },

  listPad: { paddingBottom: 116 },
  listSingle: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
    marginBottom: 8,
    ...softShadow,
  },

  form: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    ...softShadow,
  },
  label: {
    color: COLORS.text,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
    marginTop: 12,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface2,
  },
  prefix: { color: COLORS.accent, fontWeight: '900', paddingLeft: 14, paddingRight: 4 },
  input: { flex: 1, minHeight: 48, color: COLORS.text, paddingHorizontal: 12, fontSize: 16 },
  primary: {
    minHeight: 50,
    borderRadius: 14,
    marginTop: 18,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: { color: COLORS.onAccent, fontSize: 14, fontWeight: '900' },

  category: { padding: 15 },
  emptyInline: { color: COLORS.muted, padding: 18, fontSize: 13 },

  insightRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  insight: {
    flex: 1,
    minHeight: 132,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 15,
    justifyContent: 'space-between',
    ...softShadow,
  },
  insightBig: {
    color: COLORS.text,
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
    marginVertical: 8,
    letterSpacing: -0.35,
  },

  bottom: {
    minHeight: 76,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    backgroundColor: COLORS.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
    paddingBottom: Platform.OS === 'ios' ? 8 : 4,
    ...navShadow,
  },
  tab: {
    flex: 1,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
  },
  tabIcon: { color: COLORS.muted, fontSize: 18, lineHeight: 21, fontWeight: '700' },
  tabLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '700', marginTop: 3 },
  active: { color: COLORS.accent },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -24,
    borderWidth: 4,
    borderColor: COLORS.surface,
    ...softShadow,
  },
  fabText: { color: COLORS.onAccent, fontSize: 28, lineHeight: 30, fontWeight: '500' },

  search: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
    paddingHorizontal: 14,
    marginBottom: 8,
    fontSize: 16,
  },
  filters: { paddingVertical: 5, paddingRight: 16 },
  filterChip: {
    minHeight: 36,
    paddingHorizontal: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    justifyContent: 'center',
    marginRight: 7,
  },
  filterChipActive: { borderColor: COLORS.accent, backgroundColor: COLORS.accentSoft },
  filterChipText: { color: COLORS.muted, fontSize: 11, fontWeight: '700' },
  filterChipTextActive: { color: COLORS.accent, fontWeight: '800' },

  walletRow: { paddingRight: 20, gap: 10 },
  walletCard: {
    width: 150,
    minHeight: 104,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 14,
    ...softShadow,
  },
  walletIcon: { fontSize: 20 },
  walletName: { color: COLORS.muted, fontSize: 11, fontWeight: '700', marginTop: 9 },
  walletBalance: { color: COLORS.text, fontSize: 17, fontWeight: '900', marginTop: 3 },

  setupGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  setupCard: {
    width: '48%',
    minHeight: 124,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 15,
    ...softShadow,
  },
  setupIcon: { fontSize: 22, marginBottom: 12 },

  manageRow: {
    minHeight: 62,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  manageRight: { alignItems: 'flex-end', gap: 6 },
});

export default s;
